# Generated by Django 5.0.2 on 2024-03-21 07:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cart_razor_pay_order_id_cart_razor_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='logos',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, upload_to='images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
