# Generated by Django 5.0.2 on 2024-03-22 06:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_logos'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, upload_to='images')),
                ('product_desription', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
