# Generated by Django 5.0.2 on 2024-03-22 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='product_desription',
            new_name='desription',
        ),
    ]
