# Generated by Django 3.2.9 on 2024-02-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_color_variant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_variant',
        ),
        migrations.AddField(
            model_name='product',
            name='Color_variant',
            field=models.ManyToManyField(blank=True, to='products.Colorvariant'),
        ),
        migrations.AddField(
            model_name='product',
            name='Size_variant',
            field=models.ManyToManyField(blank=True, to='products.Sizevariant'),
        ),
    ]
