# Generated by Django 3.2.9 on 2024-02-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240227_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Color_variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Size_variant',
        ),
        migrations.AddField(
            model_name='product',
            name='color_variant',
            field=models.ManyToManyField(blank=True, to='products.ColorVariant'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_variant',
            field=models.ManyToManyField(blank=True, to='products.SizeVariant'),
        ),
    ]
