# Generated by Django 3.2.9 on 2024-02-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20240227_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_desription',
        ),
    ]
